### META ###
quarkus.application.version=@project.version@

### LOGGING ###
quarkus.log.level=DEBUG
quarkus.log.category."org.hibernate".level=WARN
quarkus.log.handlers=CONSOLE

### CORS ### 
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=*
quarkus.http.cors.methods=*

### DATABASE DEV ###
%dev.quarkus.datasource.db-kind = postgresql
%dev.quarkus.datasource.db-version = 16
%dev.quarkus.datasource.username=user
%dev.quarkus.datasource.password=password
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.178.155:5433/kochwiki
%dev.quarkus.hibernate-orm.schema-management.strategy=update

### DATABASE PROD ###
%prod.quarkus.datasource.db-kind = postgresql
%prod.quarkus.datasource.db-version = 16
%prod.quarkus.datasource.username=user
%prod.quarkus.datasource.password=password
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/kochwiki
%prod.quarkus.hibernate-orm.schema-management.strategy=update